# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
# GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
# Go modules in dev branch
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  ## group all dependencies with a k8s.io prefix into a single PR.
  groups:
    kubernetes:
      patterns: [ "k8s.io/*" ]
  ignore:
  - dependency-name: "k8s.io/*"
    update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  - dependency-name: "go.etcd.io/*"
    update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  target-branch: "dev"
