---
kind: pipeline
type: docker
name: ci-pipeline-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: ci
    image: rancher/dapper:v0.6.0
    environment:
      DRONE_TAG: ${DRONE_TAG}
      DRONE_COMMIT_SHA: ${DRONE_COMMIT_SHA}
    commands:
      - dapper ci
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
      - push
      - pull_request
      - tag

  - name: github_binary_release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      checksum:
      - sha256
      files:
      - "build/hangar-*"
      title: "${DRONE_TAG}"
    when:
      event:
      - tag
      ref:
        include:
        - "refs/tags/v*"
        exclude:
        - "refs/tags/*rc*"
        - "refs/tags/*alpha*"

  - name: github_binary_prerelease
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      checksum:
      - sha256
      files:
      - "build/hangar-*"
      prerelease: true
      title: "Pre-release ${DRONE_TAG}"
    when:
      event:
      - tag
      ref:
        include:
        - "refs/tags/*rc*"
        - "refs/tags/*alpha*"

  - name: docker-publish-amd64
    pull: default
    image: rancher/dapper:v0.6.0
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
      REGISTRY: "docker.io/cnrancher"
      DRONE_TAG: ${DRONE_TAG}
      DRONE_COMMIT_SHA: ${DRONE_COMMIT_SHA}
    commands:
      - dapper docker
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
      - tag

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

node:
  instance: agent-amd64

---
kind: pipeline
name: ci-pipeline-arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: ci
    image: rancher/dapper:v0.6.0
    environment:
      PROXY:
        from_secret: proxy
      DRONE_TAG: ${DRONE_TAG}
      DRONE_COMMIT_SHA: ${DRONE_COMMIT_SHA}
    commands:
      - dapper test
      - dapper build
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
      - push
      - pull_request
      - tag
  - name: docker-publish-arm64
    pull: default
    image: rancher/dapper:v0.6.0
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
      REGISTRY: "docker.io/cnrancher"
      DRONE_TAG: ${DRONE_TAG}
      DRONE_COMMIT_SHA: ${DRONE_COMMIT_SHA}
    commands:
      - dapper docker
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
      - tag

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

node:
  instance: agent-arm64

---

kind: pipeline
name: ci-manifest-amd64

steps:
  - name: docker-publish-manifest
    pull: default
    image: rancher/dapper:v0.6.0
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
      REGISTRY: "docker.io/cnrancher"
      DRONE_TAG: ${DRONE_TAG}
      DRONE_COMMIT_SHA: ${DRONE_COMMIT_SHA}
    commands:
      - dapper docker-manifest
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
      - tag
      ref:
        include:
        - "refs/tags/v*"
        exclude:
        - "refs/tags/*rc*"
        - "refs/tags/*alpha*"

  - name: docker-publish-manifest-prerelease
    pull: default
    image: rancher/dapper:v0.6.0
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
      SKIP_LATEST_TAG: "1"
      REGISTRY: "docker.io/cnrancher"
      DRONE_TAG: ${DRONE_TAG}
      DRONE_COMMIT_SHA: ${DRONE_COMMIT_SHA}
    commands:
      - dapper docker-manifest
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - tag
      ref:
        include:
        - "refs/tags/*rc*"
        - "refs/tags/*alpha*"

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

depends_on:
  - ci-pipeline-amd64
  - ci-pipeline-arm64

node:
  instance: agent-amd64
