name: CI
on:
  pull_request:
  push:
    tags-ignore:
      - '**'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Dependencies
        run: |
          sudo apt update
          sudo apt --yes install libgpgme-dev libassuan-dev libbtrfs-dev libdevmapper-dev pkg-config gcc
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
      - name: Verify
        run: |
          ./scripts/verify.sh
      - name: Test
        run: |
          ./scripts/test.sh
      - name: Static Build
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: build --clean --snapshot
